version: "3.5"

services:
  mailhog:
    container_name: "mailhog"
    build:
      context: .
      dockerfile: docker/Dockerfile.mailhog
    image: "cactus-mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - "./.mailhog:/maildir"
    environment:
      - MH_AUTH_FILE=/maildir/auth.file
    networks:
      - default
networks:
  default:
    external:
      name: rabbitmq_net
